[6pm]
github = "michelvergnaud/6PM"
source = "github"

[ComplexNonlinearities]
github = "jatinchowdhury18/ComplexNonlinearities"
source = "github"

[BitWizzard]
github = "jpcima/BitWizzard"
source = "github"

[DelayArchitect]
github = "jpcima/DelayArchitect"
source = "github"

[EarthEcho]
github = "JimmyKenMerchant/EarthEcho"
source = "github"

[HarmonicExciter]
gdaw = "lv2-HarmonicExciter"
github = "brummer10/HarmonicExciter"
source = "github"

[Livecut-LV2]
github = "eventual-recluse/Livecut-LV2"
source = "github"

[NEL-19]
github = "Mrugalla/NEL-19"
source = "github"

[PAPU]
github = "FigBug/PAPU"
source = "github"

[PLEBTracker]
github = "danfrz/PLEBTracker"
source = "github"

[Pigiron]
github = "plewto/Pigiron"
source = "github"

[Q]
github = "cycfi/Q"
source = "github"

[RP2A03]
github = "FigBug/RP2A03"
source = "github"

[Rumor]
github = "brummer10/Rumor"
source = "github"

[SID]
github = "FigBug/SID"
source = "github"

[SN76489]
github = "FigBug/SN76489"
source = "github"

[SwankyAmp]
github = "resonantdsp/SwankyAmp"
source = "github"

[Temperament]
github = "timcsy/Temperament"
source = "github"

[Voc]
github = "FigBug/Voc"
source = "github"

[VocProc]
github = "Stazed/vocproc"
source = "github"

[Wavetable]
github = "FigBug/Wavetable"
source = "github"

[b-step]
github = "surge-synthesizer/b-step"
source = "github"

[bintracker]
github = "bintracker/bintracker"
source = "github"

[bitcrusher-lv2]
gdaw = "lv2-bitcrusher"
github = "krig/bitcrusher.lv2"
source = "github"

[caps-lv2]
gdaw = "lv2-caps"
github = "moddevices/caps-lv2"
source = "github"

[dm-GrainDelay]
github = "davemollen/dm-GrainDelay"
source = "github"

[drmr]
github = "nicklan/drmr"
source = "github"

[emutrix]
github = "linuxmao-org/emutrix"
source = "github"

[fogpad]
gdaw = "vst3-fogpad"
github = "igorski/fogpad"
source = "github"

[ingen]
gitlab = "drobilla/ingen"
source = "gitlab"

[jack-smf-utils]
github = "zynthian/jack-smf-utils"
source = "github"

[jamrtc]
github = "lminiero/jamrtc"
source = "github"

[joy2jack]
github = "hauspie/joy2jack"
source = "github"

[klick]
github = "dsacre/klick"
source = "github"

[libresample]
github = "minorninth/libresample"
source = "github"

[lv2-Uhhyou-Plugins]
github = "ryukau/LV2Plugins"
source = "github"

[machina]
gitlab = "drobilla/machina"
source = "gitlab"

[master-me]
github = "trummerschlunk/master_me"
source = "github"

[mididings]
github = "noedigcode/mididings"
source = "github"

[midisheetmusic]
github = "wang1ang/midisheetmusic"
source = "github"

[minaton]
gdaw = "lv2-minaton"
github = "thunderox/Minaton"
source = "github"

[mod-arpeggiator-lv2]
gdaw = "lv2-mod-arpeggiator"
github = "moddevices/mod-arpeggiator-lv2"
source = "github"

[monique-monosynth]
github = "surge-synthesizer/monique-monosynth"
source = "github"

[snhirsch/mustang-midi-bridge]
github = "snhirsch/mustang-midi-bridge"
source = "github"

[osxmidi]
github = "osxmidi/SFZero-X"
source = "github"

[postfish]
gitlab = "https://gitlab.xiph.org/xiph/postfish"
source = "gitlab"

[protoplug-free]
github = "pluginguru/protoplug-free"
source = "github"

[realtimeconfigquickscan]
github = "raboof/realtimeconfigquickscan"
source = "github"

[regrader]
gdaw = "vst3-regrader"
github = "igorski/regrader"
source = "github"

[raul]
gitlab = "drobilla/raul"
source = "gitlab"

[ripchord]
github = "trackbout/ripchord"
source = "github"

[sassy]
github = "jarikomppa/sassy"
source = "github"

[slPlugins]
gdaw = "SocaLabs-plugins"
github = "FigBug/slPlugins"
source = "github"

[sooperlooper-lv2-plugin]
gdaw = "lv2-sooperlooper"
github = "moddevices/sooperlooper-lv2-plugin"
source = "github"

[stereog]
gdaw = "lv2-stereog"
github = "ecashin/stereog"
source = "github"

[tamgamp-lv2]
gdaw = "lv2-tamgamp"
github = "sadko4u/tamgamp.lv2"
source = "github"

[tap-lv2]
gdaw = "lv2-tap"
github = "moddevices/tap-lv2"
source = "github"

[transformant]
gdaw = "vst3-transformant"
github = "igorski/transformant"
source = "github"

[vst3-Uhhyou-Plugins]
github = "ryukau/VSTPlugins"
source = "github"

[x42-plugins]
github = "x42/x42-plugins"
source = "github"

[ysfx]
github = "jpcima/ysfx"
source = "github"
